package com.demo.flightbooking.ai;

import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.service.AiServices;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * AI-powered test scenario generator for the Flight Booking framework.
 *
 * Takes a feature description as input, calls an LLM via LangChain4j,
 * and outputs structured test scenarios in Markdown format.
 *
 * Three modes: PRD-to-comprehensive, negative-only, and regression suite.
 * Does not generate executable code — outputs scenarios for human review.
 *
 * @see ScenarioGeneratorService
 * @see ScenarioGeneratorRunner
 */
public class AiScenarioGenerator {

    private static final Logger logger = LogManager.getLogger(AiScenarioGenerator.class);

    private final ScenarioGeneratorService service;

    /**
     * Creates an AiScenarioGenerator using the provider configured in
     * config.properties.
     */
    public AiScenarioGenerator() {
        this(AiModelFactory.create(0.3, false));
    }

    /**
     * Creates an AiScenarioGenerator with an explicitly provided ChatModel.
     * Used for testing with mock models or explicit provider override.
     */
    public AiScenarioGenerator(ChatModel model) {
        this.service = AiServices.create(ScenarioGeneratorService.class, model);
        logger.info("AiScenarioGenerator initialized with model: {}", model.getClass().getSimpleName());
    }

    /**
     * Mode 1: PRD → Comprehensive test cases.
     * Generates full coverage: positive, negative, boundary, edge cases.
     *
     * @param feature The feature description or PRD text.
     * @return Path to the generated scenario report.
     */
    public Path generateFromPrd(String feature) {
        logger.info("=== Scenario Generation Started (Mode: PRD → Comprehensive) ===");
        logger.info("Feature input length: {} chars", feature.length());

        String scenarios = service.generateFromPrd(feature);
        validateOutputFormat(scenarios);

        String header = "# AI-Generated Test Scenarios — Comprehensive\n\n" +
                "> **Mode:** PRD → Comprehensive\n" +
                "> **Generated by:** AiScenarioGenerator\n" +
                "> **Model:** " + AiModelFactory.getModelName() + "\n" +
                "> **Status:** DRAFT — requires human review before implementation\n\n" +
                "---\n\n";

        return writeReport(header + scenarios, "scenario-report-comprehensive.md");
    }

    /**
     * Mode 2: Negative testing only.
     * Generates breaking scenarios: invalid inputs, boundary violations, malformed
     * data.
     *
     * @param feature The feature description to break.
     * @return Path to the generated scenario report.
     */
    public Path generateNegativeTests(String feature) {
        logger.info("=== Scenario Generation Started (Mode: Negative Testing) ===");
        logger.info("Feature input length: {} chars", feature.length());

        String scenarios = service.generateNegativeTests(feature);
        validateOutputFormat(scenarios);

        String header = "# AI-Generated Test Scenarios — Negative Testing\n\n" +
                "> **Mode:** Negative Testing Only\n" +
                "> **Generated by:** AiScenarioGenerator\n" +
                "> **Model:** " + AiModelFactory.getModelName() + "\n" +
                "> **Status:** DRAFT — requires human review before implementation\n\n" +
                "---\n\n";

        return writeReport(header + scenarios, "scenario-report-negative.md");
    }

    /**
     * Mode 3: Regression suite after a code change.
     * Generates prioritized scenarios aware of existing tests.
     *
     * @param changeDescription What changed in the codebase.
     * @return Path to the generated scenario report.
     */
    public Path generateRegressionSuite(String changeDescription) {
        logger.info("=== Scenario Generation Started (Mode: Regression Suite) ===");
        logger.info("Change description length: {} chars", changeDescription.length());

        String scenarios = service.generateRegressionSuite(changeDescription);
        validateOutputFormat(scenarios);

        String header = "# AI-Generated Test Scenarios — Regression Suite\n\n" +
                "> **Mode:** Regression Suite (post-change)\n" +
                "> **Generated by:** AiScenarioGenerator\n" +
                "> **Model:** " + AiModelFactory.getModelName() + "\n" +
                "> **Status:** DRAFT — requires human review before implementation\n\n" +
                "---\n\n";

        return writeReport(header + scenarios, "scenario-report-regression.md");
    }

    private static final String TABLE_MARKER = "| TID |";

    /**
     * Light sanity check on AI output format.
     * Warns if expected table markers are missing but does not block report
     * generation.
     */
    private void validateOutputFormat(String scenarios) {
        if (scenarios == null || scenarios.isBlank()) {
            logger.warn("AI returned empty output — report will have no scenarios");
        } else if (!scenarios.contains(TABLE_MARKER)) {
            logger.warn("AI output may not follow expected table format (missing '{}' marker). " +
                    "Review the generated report carefully.", TABLE_MARKER);
        } else {
            logger.info("Output format check passed — table marker found");
        }
    }

    private Path writeReport(String content, String fileName) {
        Path outputPath = Paths.get("target", fileName);

        try {
            Files.createDirectories(outputPath.getParent());
            Files.writeString(outputPath, content);
            logger.info("Report written to: {}", outputPath.toAbsolutePath());
            logger.info("=== Scenario Generation Complete. Report: {} ===", outputPath);
        } catch (IOException e) {
            logger.error("Failed to write scenario report: {}", outputPath, e);
            throw new RuntimeException("Failed to write scenario report", e);
        }

        return outputPath;
    }
}
