package com.demo.flightbooking.ai;

import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.service.AiServices;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.nio.file.*;

/**
 * Generates AI-powered executive summaries from Surefire XML test results.
 * Advisory only — does not affect build status.
 *
 * @see TestSummaryService
 */
public class AiTestSummaryGenerator {

    private static final Logger logger = LogManager.getLogger(AiTestSummaryGenerator.class);

    private final TestSummaryService service;

    public AiTestSummaryGenerator() {
        this(AiModelFactory.create());
    }

    public AiTestSummaryGenerator(ChatModel model) {
        this.service = AiServices.create(TestSummaryService.class, model);
    }

    /**
     * Generates a summary report based on parsed Surefire XML results.
     */
    public Path generateSummary() {

        logger.info("=== AI Test Summary Generation Started ===");

        String testData = readSurefireReports();

        if (testData.isBlank()) {
            logger.warn("No surefire data found — skipping summary");
            return null;
        }

        String summary = service.generateSummary(testData);

        if (summary == null || summary.isBlank()) {
            logger.warn("AI returned empty summary — skipping report generation");
            return null;
        }

        return writeReport(summary);
    }

    /**
     * Reads surefire XML reports for summary input.
     */
    private String readSurefireReports() {
        Path dir = Paths.get("target", "surefire-reports");

        if (!Files.exists(dir)) {
            return "";
        }

        StringBuilder content = new StringBuilder();
        int maxFiles = 2; // Limit XML files processed
        int count = 0;

        try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir, "*.xml")) {
            for (Path file : stream) {

                // Truncate large XML files
                String fileContent = Files.readString(file);

                String trimmedContent = fileContent.length() > 2000
                        ? fileContent.substring(0, 2000)
                        : fileContent;

                content.append(trimmedContent).append("\n\n");

                count++;
                if (count >= maxFiles)
                    break;
            }
        } catch (IOException e) {
            logger.error("Error reading surefire reports", e);
        }

        return content.toString();
    }

    private Path writeReport(String summary) {
        Path path = Paths.get("target", "ai-summary-report.md");

        String content = """
                # AI Test Execution Summary

                > Generated by: AiTestSummaryGenerator
                > Status: DRAFT — requires human validation

                ---

                """ + summary;

        try {
            Files.createDirectories(path.getParent());
            Files.writeString(path, content);
            logger.info("Summary report written: {}", path.toAbsolutePath());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        return path;
    }
}